---
- name: Install common Development tools
  roles:
# Install Java JDK
    - role: gantsign.java
      tags:
        - java
      java_version: 8u121

    # Increase the number of files that can be watched.
    # https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
    - role: gantsign.inotify
      inotify_max_user_watches: 524288

    - role: geerlingguy.nodejs
      tags:
        - nodejs
      nodejs_version: 6.x
      nodejs_install_npm_user: vagrant
      nodejs_npm_global_packages:
        - name: grunt-cli
        - name: grunt-init
        - name: gulp-cli
        - name: npm-check-updates
        - name: typescript
        - name: ts-node
        - name: typings

  # Install and configure IntelliJ IDEA IDE
    - role: gantsign.intellij
      tags:
        - java
        - gui
        - intellij
      intellij_edition: community
      intellij_jdk_home: "{{ ansible_local.java.general.home }}"
      intellij_default_maven_home: "{{ ansible_local.maven.general.home }}"
      users:
        - username: cainbro
          intellij_jdks:
            - name: '1.8'
              home: "{{ ansible_local.java.general.home }}"
          intellij_default_jdk: '1.8'
          intellij_disabled_plugins:
            - CVS
            - com.intellij.uiDesigner
            - org.jetbrains.android
            - TestNG-J
            - hg4idea
            - Subversion
            - AntSupport
            - DevKit
            - ClearcasePlugin
            - CloudBees
            - CloudFoundry
            - Geronimo
            - GlassFish
            - Heroku
            - JBoss
            - JSR45Plugin
            - OpenShift
            - Resin
            - StrutsAssistant
            - WebSphere
            - Weblogic
            - com.intellij.appengine
            - com.intellij.aspectj
            - com.intellij.dmserver
            - com.intellij.flex
            - com.intellij.gwt
            - com.intellij.seam
            - com.intellij.seam.pageflow
            - com.intellij.seam.pages
            - com.intellij.struts2
            - com.intellij.tapestry
            - com.intellij.vaadin
            - com.intellij.velocity
            - org.coffeescript
            - org.intellij.grails
            - org.jetbrains.plugins.haml
            - org.jetbrains.plugins.stylus
            - TFS
            - PerforceDirectPlugin
          intellij_codestyles:
            - name: GantSign
              url: 'https://raw.githubusercontent.com/gantsign/code-style-intellij/1.0.0/GantSign.xml'
          intellij_active_codestyle: GantSign
          intellij_plugins:
            - CheckStyle-IDEA
            - Lombook Plugin
          intellij_license_key_path: '{{ intellij_license_key_path }}'

    # Add items to DockbarX launcher
    - role: gantsign.pin-to-launcher
      tags:
        - gui
      pin_to_launcher: unity
      pin_to_launcher_favorites:
        - application: ubiquity.desktop
          when_desktop: unity
        - application: terminator.desktop
        - application: org.gnome.Nautilus.desktop
          when_desktop: unity
        - application: virtualbox.desktop
        - application: google-chrome.desktop
        - application: Postman.desktop
        - application: atom.desktop
        - application: sublime-text.desktop
        - application: code.desktop
        - application: "{{ ansible_local.intellij.general.desktop_filename if (ansible_local is defined and ansible_local.intellij is defined) else omit }}"
        - application: ubuntu-software-center.desktop
          when_desktop: unity
        - application: unity-control-center.desktop
          when_desktop: unity
        - unity: running-apps
        - unity: expo-icon
        - unity: devices
