---
# apps to install
username: bcain
general:
  local_home: "{{ lookup('env', 'HOME') }}"
  ohmyzsh_custom_path: "{{ lookup('env', 'HOME') }}/.zsh_custom"

dotfiles_repo: "https://bcain@bitbucket.org/bcain/dotfiles.git"
dotfiles_repo_dest: "~/git/dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .bashrc
  - .gitconfig
  - .gitignore
  - .zsh_favlist
  - .zshrc
  
applications:
  - git
  - git-extras
  - httpie
  - curl
  - wget
  - zsh
  - kubectl
  - kubernetes-helm
  - ssh-copy-id
  - node
  - nvm
  - openssl
  - tmux
  - coreutils
  - python
  - tree
  - ack
  - nginx


# homebrew cask apps
cask_apps:
  - google-chrome
  - google-backup-and-sync
  - firefox
  - atom
  - sublime-text
  - slack
  - iterm2
  - docker
  - vagrant
  - virtualbox
  - spotify
  - alfred
  - minikube
  - dropbox
  - transmit
  - licecap
  - evernote
  - visual-studio-code
  - webstorm
  - intellij-idea-ce
  - postman
  - java
  - java8
  - keepassx
  - microsoft-teams
  - kdiff3
  - sourcetree
  - font-firacode-nerd-font
  - font-firamono-nerd-font
  - font-monofur-for-powerline
  - font-menslo-nerd-font
  - font-meslo-nerd-font
  - font-meslo-for-powerline
  - font-liberation-mono-for-powerline
  - font-liberationmono-nerd-font
  - spectacle

